services:
  - type: web
    name: mograder-demo
    runtime: docker
    dockerfilePath: demo/Dockerfile
    plan: free
  - type: web
    name: mograder-editor
    runtime: docker
    dockerfilePath: demo/Dockerfile.editor
    plan: free
