[[assignments]]
name = "A1. Introduction to Scientific Machine Learning (Not Assessed)"
id = 45061
cmid = 2452685
duedate = 1737633600
  [[assignments.files]]
  name = "A1-Intro-to-SciML (1).zip"
  url = "https://moodle-staging.warwick.ac.uk/pluginfile.php/3814762/mod_assign/introattachment/0/A1-Intro-to-SciML%20%281%29.zip"

[[assignments]]
name = "A2. Sensitivity Analysis"
id = 45062
cmid = 2452686
duedate = 1738238400
files = []

[[assignments]]
name = "A3. Linear Regression"
id = 45063
cmid = 2452687
duedate = 1738843200
files = []

[[assignments]]
name = "A4. Gaussian Process Regression"
id = 45064
cmid = 2452688
duedate = 1739448000
files = []

[[assignments]]
name = "A5. Neural Networks"
id = 45065
cmid = 2452689
duedate = 1740052800
files = []

[[assignments]]
name = "A6. Physics-Informed Neural Networks"
id = 45066
cmid = 2452690
duedate = 1740657600
files = []

[[assignments]]
name = "A7.  Unsupervised Learning"
id = 45067
cmid = 2452691
duedate = 1741262400
files = []

[moodle]
csv = "moodle_worksheet.csv"
url = "https://moodle-staging.warwick.ac.uk"
course_id = 65017

[[moodle.assignments]]
name = "A1. Introduction to Scientific Machine Learning (Not Assessed)"
id = 45061
cmid = 2452685
duedate = 1737633600
  [[moodle.assignments.files]]
  name = "A1-Intro-to-SciML (1).zip"
  url = "https://moodle-staging.warwick.ac.uk/pluginfile.php/3814762/mod_assign/introattachment/0/A1-Intro-to-SciML%20%281%29.zip"

[[moodle.assignments]]
name = "A2. Sensitivity Analysis"
id = 45062
cmid = 2452686
duedate = 1738238400
files = []

[[moodle.assignments]]
name = "A3. Linear Regression"
id = 45063
cmid = 2452687
duedate = 1738843200
files = []

[[moodle.assignments]]
name = "A4. Gaussian Process Regression"
id = 45064
cmid = 2452688
duedate = 1739448000
files = []

[[moodle.assignments]]
name = "A5. Neural Networks"
id = 45065
cmid = 2452689
duedate = 1740052800
files = []

[[moodle.assignments]]
name = "A6. Physics-Informed Neural Networks"
id = 45066
cmid = 2452690
duedate = 1740657600
files = []

[[moodle.assignments]]
name = "A7.  Unsupervised Learning"
id = 45067
cmid = 2452691
duedate = 1741262400
files = []

